name: watch_twitter
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: python-watch-twitter
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy==4.4.0
      - name: Run script
        run: |
          python main.py
        env:
          TZ: "Asia/Tokyo"
          FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TO_ADDRESS: ${{ secrets.TO_ADDRESS }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}